"""v0.4 execution core.

One deterministic path: a validated ``GamePlan`` is interpreted by
``Interpreter``, which dispatches only declared tool operations from a
``ToolRegistry``. ``playtest`` is the gate that a plan must pass before it can
be shown as playable.
"""
from .artifacts import GameArtifact, VerificationResult, build_artifact, verification_id
from .capability import AXES, Capability, CapabilityReport, capability_check, capability_matrix
from .cards import CardRef, decode, encode
from .compositions import (
                     composition_samples,
                     exchange_compare_composition,
                     exchange_strategy,
                     exchange_suit_score_composition,
)
from .contracts import Observation, OperationSpec, ToolError, ToolRegistry, ToolSpec
from .corpus import coverage_report, load_corpus
from .evaluation import (
                     DEFAULT_EVALUATION_STRATEGIES,
                     Distribution,
                     SimulationEvaluation,
                     SimulationRun,
                     evaluate_simulations,
)
from .interpreter import Interpreter
from .invariants import (
                     card_conservation,
                     never_finishes_without_winners_or_scores,
                     non_negative_scores,
                     view_is_safe,
                     zone_conservation,
)
from .ir import (
                     ArithmeticIR,
                     BlackjackIR,
                     GoFishIR,
                     PokerIR,
                     RulesIR,
                     SheddingIR,
                     UnoIR,
                     WarIR,
                     WhistIR,
                     check_ir,
                     host_compile,
                     is_host_compiled,
                     parse_ir,
                     required_axes,
)
from .macro_library import MATCH_TURN, PLAN_MACROS, default_macros
from .macros import MacroRegistry, MacroSpec, expand_macro, promotion_report, validate_macro, wire
from .plan import ActionDescriptor, ActionInputDescriptor, FlowCase, FlowNode, GamePlan, ToolBinding, ToolCall
from .plans import (
                     arithmetic_plan,
                     blackjack_plan,
                     crazy_eights_plan,
                     five_card_poker_plan,
                     go_fish_plan,
                     uno_plan,
                     war_plan,
                     whist_plan,
)
from .playtest import (
                     PlaytestReport,
                     boundary_first,
                     card_first,
                     first_legal,
                     goal_first,
                     playtest,
                     random_legal,
                     resilient_first,
)
from .policy import bet_first, bot_action, composed_action, run_bots
from .reference import REFERENCE_GAMES, build_plan, ensure_playtested, list_reference_games
from .registry import core_registry
from .rules import (
                     CompiledRules,
                     CompileError,
                     ComposedRulesIR,
                     CompositionReport,
                     compile_composed,
                     derive_requirements,
                     ir_hash,
                     resolve_composition,
)
from .session import Session, SessionStore
from .verify import (
                     ContractReport,
                     compare_traces,
                     contract_check,
                     publish_composed,
                     record_trace,
                     replay_trace,
                     verify_composed,
                     verify_plan,
)
from .zone_tools import ZonesTool
from .zones import (
                     ZONES_KEY,
                     all_cards,
                     apply_moves,
                     assert_unique_ownership,
                     find_zone_of,
                     ownership_problems,
                     select_cards,
                     top_card,
                     zone_cards,
                     zone_table,
)

__all__ = [
                     "AXES",
                     "DEFAULT_EVALUATION_STRATEGIES",
                     "MATCH_TURN",
                     "PLAN_MACROS",
                     "REFERENCE_GAMES",
                     "ZONES_KEY",
                     "ActionDescriptor",
                     "ActionInputDescriptor",
                     "ArithmeticIR",
                     "BlackjackIR",
                     "Capability",
                     "CapabilityReport",
                     "CardRef",
                     "CompileError",
                     "CompiledRules",
                     "ComposedRulesIR",
                     "CompositionReport",
                     "ContractReport",
                     "Distribution",
                     "FlowCase",
                     "FlowNode",
                     "GameArtifact",
                     "GamePlan",
                     "GoFishIR",
                     "Interpreter",
                     "MacroRegistry",
                     "MacroSpec",
                     "Observation",
                     "OperationSpec",
                     "PlaytestReport",
                     "PokerIR",
                     "RulesIR",
                     "Session",
                     "SessionStore",
                     "SheddingIR",
                     "SimulationEvaluation",
                     "SimulationRun",
                     "ToolBinding",
                     "ToolCall",
                     "ToolError",
                     "ToolRegistry",
                     "ToolSpec",
                     "UnoIR",
                     "VerificationResult",
                     "WarIR",
                     "WhistIR",
                     "ZonesTool",
                     "all_cards",
                     "apply_moves",
                     "arithmetic_plan",
                     "assert_unique_ownership",
                     "bet_first",
                     "blackjack_plan",
                     "bot_action",
                     "boundary_first",
                     "build_artifact",
                     "build_plan",
                     "capability_check",
                     "capability_matrix",
                     "card_conservation",
                     "card_first",
                     "check_ir",
                     "compare_traces",
                     "compile_composed",
                     "composed_action",
                     "composition_samples",
                     "contract_check",
                     "core_registry",
                     "coverage_report",
                     "crazy_eights_plan",
                     "decode",
                     "default_macros",
                     "derive_requirements",
                     "encode",
                     "ensure_playtested",
                     "evaluate_simulations",
                     "exchange_compare_composition",
                     "exchange_strategy",
                     "exchange_suit_score_composition",
                     "expand_macro",
                     "find_zone_of",
                     "first_legal",
                     "five_card_poker_plan",
                     "go_fish_plan",
                     "goal_first",
                     "host_compile",
                     "ir_hash",
                     "is_host_compiled",
                     "list_reference_games",
                     "load_corpus",
                     "never_finishes_without_winners_or_scores",
                     "non_negative_scores",
                     "ownership_problems",
                     "parse_ir",
                     "playtest",
                     "promotion_report",
                     "publish_composed",
                     "random_legal",
                     "record_trace",
                     "replay_trace",
                     "required_axes",
                     "resilient_first",
                     "resolve_composition",
                     "run_bots",
                     "select_cards",
                     "top_card",
                     "uno_plan",
                     "validate_macro",
                     "verification_id",
                     "verify_composed",
                     "verify_plan",
                     "view_is_safe",
                     "war_plan",
                     "whist_plan",
                     "wire",
                     "zone_cards",
                     "zone_conservation",
                     "zone_table",
]
